language: node_js

# build matrix
os:
  - linux
  - osx
node_js:
  - 4
  - 5
  - 6
compiler:
  - gcc
env:
  - REQUIRED_TESTS=false
  - REQUIRED_TESTS=true

# allow the ecosystem tests to fail. these failures should be
# communicated to the maintainers of the failing modules
matrix:
  allow_failures:
    - env: REQUIRED_TESTS=false
  fast_finish: true

before_install:
# install gcc 4.8 on osx using homebrew
- sh -c '[[ "$TRAVIS_OS_NAME" == "osx" ]] && brew tap homebrew/versions'
- sh -c '[[ "$TRAVIS_OS_NAME" == "osx" ]] && brew update'
- sh -c '[[ "$TRAVIS_OS_NAME" == "osx" ]] && brew install gcc48'
# install gcc 4.8 on linux using apt
- sh -c '[[ "$TRAVIS_OS_NAME" == "linux" ]] && sudo apt-get install python-software-properties'
- sh -c '[[ "$TRAVIS_OS_NAME" == "linux" ]] && sudo add-apt-repository ppa:ubuntu-toolchain-r/test'
- sh -c '[[ "$TRAVIS_OS_NAME" == "linux" ]] && sudo apt-get update'
- sh -c '[[ "$TRAVIS_OS_NAME" == "linux" ]] && sudo apt-get install gcc-4.8'
- sh -c '[[ "$TRAVIS_OS_NAME" == "linux" ]] && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50'

script:
- sh -c '[[ "$REQUIRED_TESTS" == "true" ]] && npm test'
- sh -c '[[ "$REQUIRED_TESTS" == "false" ]] && npm run ci'

notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/54f8a1e753f859f5ca1a
    on_start: never
    on_failure: change

deploy:
  provider: npm
  email: hello@trailsjs.io
  api_key:
    secure: d/VChdWWPr8Mi6UyRUjIhjEfXHoyTCJ0z/pyNzF3yd2vpvC07fK90ka0CPxHhKyPWj7h7+ZG0FO0U8wj4YAZ8QeKIuc5rZbe1wI5yISpbnVxDKk0tYqyDFCRbmXVu7RNeLbBPN6y3fbJYdCLM14ugTfaJaBdewVTeOFGFBA712vHwu8ptWW/zw72YbH9d6C+LnAyz17ZyeAG7BvABISKv+bzuYexFaw4gv/uGNp2o//zC4FlXNcVWR3hb/cS6SWWoiPdsOZvDJTY+2J+WSEMlZ+PIZaJjfki4RbisoIg5Q3KM/WhgXwRfgma4POrGSqXvg8Yy1lqTIoZJT1SEnIj+KIOHuLoI+Rv1hc3n+Aw5Q2iMSPo/QlbolhfOhmGRkx5XIxIlKs/Vf6GJGQBf2lB5W2tgdf3UYwGbXjWOUoj+4NBotWQ4vaHlwfJb9sm66yXG9ayDkgc8Gegj6ooRC+xl8irgu/xgtSMKek6I893r/sLTnAkYcrLMUSqOp9qMBk8Zfdir978yKx4pTPBJvlnilze+cdSNMSXokKMDNF4wbaDVCyaFsoYEYNW/basaKynBiPgi4exjWH1SlXBOKA+LTr8i9ZwdGNIRDx3mxTiUHvwaYbn9tHOt8ymEwTfFe90a2XDp0+sUKEtLT+i6jF41iFQq0b/OwzWnQf3GfcDyYY=
  on:
    tags: true
    repo: trailsjs/trails
    node: 6
