language: node_js
node_js:
- '4'
- stable

notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/54f8a1e753f859f5ca1a
    on_start: never
    on_failure: change

deploy:
  provider: npm
  email: hello@trailsjs.io
  api_key:
    secure: cId4l4+KsweaGb0CFxBKu5ai2OHfKM0eWIbHIGS21G69c443LfWhNCJ88Q+J+qG8+gb+hBFvG6W46ISe0G/DdktKFjcTcBpiABHxv/Tz8kAYPsiIuXut8MV0565WaP7LWMhaAa2frZ2SWOMiGo2BDR82N1w4ORomjI6XWg/c3WjHx+aaYdt+8+En/XSkF9m/TxDNBR4mbtlajvx7BrL22IF0AmHETM7Sld+X5IkWwJ8f0t5rhrr2EUsewLfxMf7AHGoeB+U2Uha/CC6b39kgEAkU8m4Ylj0wGMKmSZl3SZcM3ZAaDk/4bAjx+le5PVStJE+gQT3bQETmBxiIHzGR9FL9zYa/yB7PwE/Yjs5qIpz6alXUt9HJRK6INNFy7bCjjhTZqHDzu2paz8NSuGvf3rwz8yT5isZLoDEEqrrwrseCICcFiV8PyKGmyyQoqArWQIasvBxKnU8Tr0nE5hWZmXavBFcDWLOwTLcT6JxecBzlFL0pbLyfrC+x/QzVKS72hVLEafemVtenbvQ0dD4CcVb9qWnss7v1Q/+H+xjdjFtmqA5j9P0sDxrnp0wvXpLFx9/oPDJeiHswKVPXIlmPriQM+k0DArjZUW//I0qiO/5NKhsrJKf/SCI4SkwMopPpOqhbdGNLOqqKvpoPOZXnearVtQ4nUVDq61evfE3Z+bQ=
  on:
    tags: true
    repo: trailsjs/trails
    node: stable
